CREATE TABLE IF NOT EXISTS expense (
	id INT PRIMARY KEY,
	user_id INT NOT NULL,
	date DATE NOT NULL,
	amount DECIMAL(6,2) NOT NULL,
	category VARCHAR(50),
	FOREIGN KEY (user_id)
		REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS user (
	id INT PRIMARY KEY,
	name VARCHAR(255)NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);