CREATE TABLE IF NOT EXISTS expense (
	id INT PRIMARY KEY,
	date DATE NOT NULL,
	amount DECIMAL(6,2) NOT NULL,
	category VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS user (
	id INT PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);